### ISSUE TITLE
Week 5 exercise - Visualization

### ISSUE THREAD

**Issue by okichris90** [ajklinker/abbieklinker-MADA-portfolio#4]
Hi Abbie, 
First of all, congrats on reproducing this fantastic plot. The graph was insightful. I was able to understand the message without having to read the entire article. Good job on that!
The only caveat I could barely notice was the font of the graph. Although it's not too far off at all, but slightly noticeable. I went through your codes and saw that you tried different fonts. That was my suggestion. But it seems that none match what the authors used to create this graph. 
That's not a big deal at all. The content of your plot is more important. And you did an excellent job on that!
I actually learned from reading your codes as well. Bravo!

**Comment by ajklinker** [comment]
Hey Chris, thank you for your kind words! The font was bugging me too - I wish I could figure it out. Good work on yours as well :)
